apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: austingscontainerregistry.azurecr.io/api:latest
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: postgresql+asyncpg://postgres:dnl_challenge@postgres:5432/car_db
